### ISSUE TITLE
Variable sampling rate for stations.

### ISSUE THREAD

**Issue by maxcal** [remote-wind/remote-wind#129]
The app currently pretty much assumes that every station posts observations every 5 minutes since that was what the original ardiuno stations did.

This is not really that noticeable except in the graphs for example since it uses a 5 minute tick on the X axis where the results can be somewhat strange.

**Comment by maxcal** [comment]
@karl-petter  Am I correct in that each of the ardiuno stations basically start reporting when they are booted and then report again after a 5 minute interval, rather than according to the clock?

**Comment by karl-petter** [comment]
@maxcal correct and that is how it has been working all the time
