### ISSUE TITLE
DNS settings

### ISSUE THREAD

**Issue by maxcal** [remote-wind/remote-wind#130]
The DNS settings still seem to be off since the root domain `http://blast.nu` is unreachable. Can you please try running `heroku domains:add blast.nu` @karl-petter or check the setting on the domain provider side that it points to `remote-wind.herokuapp.com`?

**Comment by maxcal** [comment]
https://devcenter.heroku.com/articles/custom-domains#add-a-custom-root-domain

**Comment by karl-petter** [comment]
Binero does not support A records for the root domain for the top domain .nu. This it has to be a redirect from blast.nu to www.blast.nu and thus only www.blast.nu should be used by the app and the clients.

**Comment by maxcal** [comment]
Can you set the redirect on Binero? Not sure thats possible on heroku.

**Comment by karl-petter** [comment]
There is already an redirect to www.blast.nu
