### ISSUE TITLE
Remove "legacy" ardiuno dead code. 

### ISSUE THREAD

**Issue by maxcal** [remote-wind/remote-wind#135]
@karl-petter Am I correct in that all the current arduino units post to `/stations/:station_id/observations` and that none of the use the old short form `b: 1, s: 2` params?

If so thats quite a lot of cruft and dead code that can be removed.

**Comment by maxcal** [comment]
Most of these methods are marked with `@todo - CLEANUP` in PR #134

**Comment by karl-petter** [comment]
There should be none running the old firmware if they are they should upgrade :) So it's fine to remove that.
