### ISSUE TITLE
Include stations without observations in lists for logged in users 

### ISSUE THREAD

**Issue by karl-petter** [remote-wind/remote-wind#138]
Stations not having any observations are not included in the lists and for not logged in users this makes sense since there is no interest in a station without data. But for someone adding new stations it is quite strange to not see the newly created station anywhere.

**Comment by maxcal** [comment]
See #122

**Comment by maxcal** [comment]
I think what we should also do is setup a owner role when creating new stations. And add it manually for the existing stations. There is a `user_id` column on stations but this allows us to use m2m and keep the role based authorization in one place.

**Comment by karl-petter** [comment]
Can you elaborate on that a bit more? What would it allow us to do? And what would the change be from a user point of view?

**Comment by maxcal** [comment]
The owners of a station would get elevated priveleges, but just for a station. The main difference from user pov is that a station could have several owners who can admin. Nice for clubs for example

**Comment by karl-petter** [comment]
Aah great if one station can have many owners.

**Comment by maxcal** [comment]
Does the station hardware have an off switch? I'm working on adding a button on the backend that lets you set the stations status to `deactived` and it will automatically change status back to `active` if the station starts broadcasting. Which might be a problem if it keeps sending observations until the battery dies.

**Comment by karl-petter** [comment]
No they do not have switch, they broadcast when powered. But why a button to set it to deactivated?

**Comment by maxcal** [comment]
You can read in #122 what the different states represent but basically setting a station as deactivated should hide it in the UI for everyone except the owners and admins. So a seasonal station should be set to deactivated if its put away for the summer.

**Comment by karl-petter** [comment]
Can a deactivated station still send in data and have it stored? For instance a user wants to test out good spots before making it public or just want to see the data for her self? Or should there be a another `:hidden` state?

**Comment by maxcal** [comment]
I'm looking through the code now  and there are two bugs 

1. The ETag cache key does not take user authentication into account.
2. The  ETag cache key is based on `Observations.last.created_at` thus creating a new station does not invalidate the cache

**Comment by maxcal** [comment]
Also `Station.with_observations` does not return stations without observations which is a bug and somewhat puzzling since it uses `eager_load` to join the observations which should give a `LEFT OUTER JOIN`
