### ISSUE TITLE
Switch Google Maps for Leaflet. 

### ISSUE THREAD

**Issue by maxcal** [remote-wind/remote-wind#139]
I have some new features I would like to add to the map.

 But I would like to to consider if we should switch to [Leaflet](http://leafletjs.com/) first:

> Leaflet is designed with simplicity, performance and usability in mind. It works efficiently across all major desktop and mobile platforms, can be extended with lots of plugins, has a beautiful, easy to use and well-documented API and a simple, readable source code that is a joy to contribute to.

Developing for the Google Maps API is really frustrating since the API code is only available in a obfuscated form, so the error messages are totally incomprensible. Most of the "plugins" are one man affairs hosted on google code (that a big warning flag).

Any thoughts @karl-petter?

**Comment by karl-petter** [comment]
Leaflet is great! I have used it a couple of times, e.g. for the engine that create these https://yelloworb.com/privat/trailstories/skridskohelg2016-10-15-16/

**Comment by maxcal** [comment]
You can use different map sources with leaflet right?

**Comment by karl-petter** [comment]
I'm quite sure, I use Thunderforest maps for the things I done but I'm quite sure I seen it over Google maps.
