### ISSUE TITLE
More stations from vägverket

### ISSUE THREAD

**Issue by maxcal** [remote-wind/remote-wind#146]
It would be pretty cool if we had some of the rest of the swedish coast and especially around key kitesurfing spots.

VV has the following stations that are interesting:

Gotland
- Klintehamn 
- Näs 
- Östergarn

Sthlm
- Dalarö (sthlm)
- Nynäshamn

Öland:
- Ölandsbron hög
- Albrunna (Öland)
- Sandby (Öland) 
- Borgholm (Öland)
- Möcklösund (Karlskrona)

Skåne:
- Åhus
- Örnahusen
- Smygehamn
- Lernacken
- Högbron SÖ
- Landskrona S
- Löddeköpinge
- Höganäs S
- Båstad V
- Brotorpet

Halland 
- Hökafältet
- Halmstad
- Brotorpet
- Nygård
- Mariedal

Västra Götaland
- Fiskebäck
- Bokenäs

**Comment by karl-petter** [comment]
They are now added to the Node-RED poster and it is posting the values. Though none are created on the server. Please feel free to do that.
Here are their slugs and coordinates:
```
[["trafikverket_nynashamn", "POINT (17.92341 58.9343872)"],
["trafikverket_borgholm", "POINT (16.73219 56.88985)"],
["trafikverket_klintehamn", "POINT (18.1841087 57.4022064)"],
["trafikverket_nas", "POINT (18.2801781 57.1313)"],
["trafikverket_albrunna", "POINT (16.4066257 56.32067)"],
["trafikverket_sandby", "POINT (16.6184483 56.5693436)"],
["trafikverket_olandsbron_hog", "POINT (16.3876362 56.6803741)"],
["trafikverket_mocklosund", "POINT (15.7429752 56.13716)"],
["trafikverket_ostergarn", "POINT (18.8206844 57.428318)"],
["trafikverket_bastad v", "POINT (12.7268848 56.4340324)"],
["trafikverket_smygehamn", "POINT (13.3558693 55.3389931)"],
["trafikverket_loddekopinge", "POINT (13.0153866 55.74928)"],
["trafikverket_ornahusen", "POINT (14.2562866 55.4482)"],
["trafikverket_ahus", "POINT (14.2699652 55.9133644)"],
["trafikverket_landskrona_s", "POINT (12.8885012 55.8577)"],
["trafikverket_lernacken", "POINT (12.8947182 55.5653152)"],
["trafikverket_nygard", "POINT (12.289094 57.0714531)"],
["trafikverket_brotorpet", "POINT (12.7020369 56.724308)"],
["trafikverket_bokenas", "POINT (11.5640793 58.29175)"],
["trafikverket_halmstad", "POINT (12.904788 56.6367073)"],
["trafikverket_mariedal", "POINT (11.9815979 57.40679)"],
["trafikverket_fiskeback", "POINT (11.8635559 57.64441)"]]
```

**Comment by maxcal** [comment]
@karl-petter could you merge the PR, push to heroku and and run `heroku run bin/rake stations:import`.

**Comment by karl-petter** [comment]
Done but none of the appear in http://www.blast.nu/stations

**Comment by maxcal** [comment]
I'm checking it from the heroku console and I think its because they have the status `not_initialized` and the wrong slug so that the post request to create observations fails.

**Comment by maxcal** [comment]
I think I messed up the order of the lat and long for the stations you posted. I assumed it was `POINT(lat lon)` but the new TRV stations are somewhere outside Madagascar...

**Comment by maxcal** [comment]
I have fixed the slugs and lat/lon and data is now coming in.
