### ISSUE TITLE
Show correct color for status in app/views/stations/_stations.html.erb

### ISSUE THREAD

**Issue by maxcal** [remote-wind/remote-wind#159]
```
<% unless station.active? %>
  <span class="label success">Active</span>
<% else %>
  <span class="label alert"><%= station.status %></span>
<% end %>
```

This should be fixed and extracted to a helper that uses I18n to translate the status into a human readable form and add the appopriate classes.

**Comment by karl-petter** [comment]
Why a helper? Is not `t("activerecord.attributes.station.status.#{status}", station.status)`sufficient?

**Comment by maxcal** [comment]
Becase its going to be used in several places and I dont want to repeat the implementaion. Its just a two line helper method.
