### ISSUE TITLE
Vägverket wind data

### ISSUE THREAD

**Issue by maxcal** [remote-wind/remote-wind#28]
This issue is branched out from #26 

@karl-petter wrote:

Hej,

här är lite information jag skrivit när jag testade att hämta data från Vägverket:

Testade också att läsa in data från trafikverket och det fungerar fint:
```SH
curl --user "user:password" "https://datex.vv.se/d2clientpull/weatherdataserviceBA/WeatherDataService.asmx?op=getDatex2Data" -d @datexWeather.txt -H "SOAPAction: "http://datex2.eu/wsdl/clientPull/1_0/getDatex2Data"" -H "Content-Type: text/xml; charset=utf-8"
```

Det man måste göra dock för att få stationsnamnen samt deras positioner är att man måste läsa in https://datex.vv.se/d2clientpull/metadataBA2/MeasurementSiteTablePublication_WeatherPostsService.asmx 

För att få det fungera bra med rails verkar tipset att använda Savon https://github.com/rubiii/savon

De har dock precis uppdaterat till Datex II så saker kan ha ändrats:

http://www.trafikverket.se/Om-Trafikverket/Andra-sprak/English-Engelska/The-Traffic-Information-Web-Site-Laget-i-trafiken/This-is-Datex/Technical-pages-for-subscribers/Datex-II-version-20/

**Comment by maxcal** [comment]
There is now a [open JSON/XML API](https://api.trafikinfo.trafikverket.se/API/Model).

**Comment by karl-petter** [comment]
Cool! I think I can quite quickly pull in some stations from there. Going to give it a try.

**Comment by karl-petter** [comment]
Was not too hard. Now my Node-red setup reads 9 of those stations and posts them. At the moment every 5th minute but should be enough once every hour because I do not think they update more often.
